"""Initial schema: users, sessions, tokens

Revision ID: 009e14cad2fa
Revises:
Create Date: 2025-11-22 11:13:52.755829

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "009e14cad2fa"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
